version: '3'

services:

  app-php-fpm:
    build:
      args:
        container_project_path: /var/www/
        host_project_path: ./workspace/
        uid: 1000
        user: $USER
      context: .
      dockerfile: Dockerfile
    image: app-php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./workspace/:/var/www/

  app-nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ./workspace/:/var/www/
      - ./.configs/nginx/conf.d/:/etc/nginx/conf.d/

  app-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql/

  app-phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: app-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 3333:80

volumes:
  mysql-data:
